name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ackerman123/sound-bot:latest
      - name: Delete old Docker container
        run: sudo docker rm -f sound-bot-container || true
      - name: Run Docker container
        run: sudo docker run -d --restart unless-stopped -e BOT_TOKEN=$BOT_TOKEN -e CLIENT_ID=$CLIENT_ID -p 3000:3000 --name sound-bot-container ackerman123/sound-bot
        env:
          BOT_TOKEN: ${{vars.BOT_TOKEN}}
          CLIENT_ID: ${{vars.CLIENT_ID}}
