name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          touch sound-bot.pem
          echo "$SSH_PRIVATE_KEY" > sound-bot.pem
          chmod 400 sound-bot.pem
          ssh -i "sound-bot.pem" ubuntu@ec2-13-215-159-171.ap-southeast-1.compute.amazonaws.com
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull Docker image
        run: sudo docker pull ackerman123/sound-bot:latest
      - name: Delete old Docker container
        run: sudo docker rm -f sound-bot-container || true
      - name: Run Docker container
        run: sudo docker run -d --restart unless-stopped --env-file ./.env -p 3000:3000 --name sound-bot-container ackerman123/sound-bot
